server:
  servlet:
    session:
      cookie:
        path: /
        name: connect.sid
        max-age: 86400
        domain: localhost
        http-only: true
        secure: false
spring:
  config:
    activate:
      on-profile: 'default'
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 'test-client-id'
            client-secret: 'test-client-secret'
            scope:
              - profile
              - email
  data:
    redis:
      lettuce:
        pool:
          max-active: 20
          max-idle: 20
          max-wait: 10s
          min-idle: 5
      host: localhost
      port: 6379
      password: 'mypassword'
      ssl:
        enabled: true
  cache:
    type: redis
  session:
    redis:
      namespace: tldr:session
  jpa:
    hibernate:
      ddl-auto: create-drop

github:
  client-id: 'test-client-id'
  client-secret: 'test-client-secret'
  redirect-uri: 'http://localhost:8080/login/oauth2/code'
  scopes: [ 'repo' ]
