spring:
  config:
    activate:
      on-profile: 'default'
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 'test-client-id'
            client-secret: 'test-client-secret'
            scope:
              - profile
              - email

github:
  client-id: 'test-client-id'
  client-secret: 'test-client-secret'
  redirect-uri: 'http://localhost:8080/login/oauth2/code'
  scopes: [ 'repo' ]
