server:
  servlet:
    session:
      cookie:
        path: /
        name: connect.sid
        max-age: 86400
        domain: localhost
        http-only: true
        secure: false
spring:
  config:
    activate:
      on-profile: 'default'
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 'test-client-id'
            client-secret: 'test-client-secret'
            scope:
              - profile
              - email
  data:
    redis:
      lettuce:
        pool:
          max-active: 20
          max-idle: 20
          max-wait: 10s
          min-idle: 5
      host: localhost
      port: 6379
      password: 'mypassword'
      ssl:
        enabled: true
  cache:
    type: redis
  session:
    redis:
      namespace: tldr:session
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: 'org.postgresql.Driver'
    url: 'jdbc:postgresql://postgres.tldr-api.orb.local:5432/mydatabase'
    username: 'myuser'
    password: 'secret'
    hikari:
      maximum-pool-size: 5
      max-lifetime: 1800000
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 15000
      leak-detection-threshold: 60000
      pool-name: 'tldr-hikari-pool'

github:
  client-id: 'test-client-id'
  client-secret: 'test-client-secret'
  redirect-uri: 'http://localhost:8080/login/oauth2/code'
  scopes: [ 'repo' ]
