create table account
(
    id bigint generated by default as identity,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    deleted_at timestamp with time zone,
    primary key (id)
);

create table boj_challenge
(
    id         bigint generated by default as identity,
    username   varchar(255),
    account_id bigint,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    deleted_at timestamp with time zone,
    primary key (id)
);

create table github_credential
(
    id           bigint generated by default as identity,
    access_token varchar(255),
    username     varchar(255),
    repository   varchar(255),
    account_id   bigint,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    deleted_at timestamp with time zone,
    primary key (id)
);
